### ISSUE TITLE
cliui ESM issue

### ISSUE THREAD

**Issue by addlistener** [yargs/yargs#2354] opened 2023-08-28 01:42 UTC
```
$ ts-node vspec.ts --input ../test_data --output out
/Users/ajc/hacking/proj/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ajc/hacking/proj/node_modules/string-width/index.js from /Users/ajc/hacking/proj/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/ajc/hacking/proj/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.

```

```
=> Found "cliui@8.0.1"
info Reasons this module exists
   - "yargs" depends on it
   - Hoisted from "yargs#cliui"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "348KB"
info Disk size with transitive dependencies: "552KB"
info Number of shared dependencies: 6
✨  Done in 0.12s.


=> Found "yargs@17.7.2"
info Has been hoisted to "yargs"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "1MB"
info Disk size with transitive dependencies: "1.31MB"
info Number of shared dependencies: 12
```

**Comment by shadowspawn** [comment] 2023-08-28 06:50
What version of `string-width` is being used by `cliui` in your project? Check with `npm ls string-width`.

In theory it should be `string-width@4.2.3` which is not esm.

https://github.com/yargs/cliui/blob/af3145da0ea31738c4715865a6da0ee388a94c74/package.json#L52

**Comment by shadowspawn** [comment] 2023-09-05 08:05
Duplicate of issue: https://github.com/yargs/cliui/issues/150

**Comment by shadowspawn** [comment] 2023-09-09 09:47
Original poster has found another approach, so closing this. See https://github.com/yargs/cliui/issues/150 for some additional clues (packing the program with https://github.com/vercel/pkg).

Future readers, feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.

**Closed by shadowspawn** 2023-09-09 09:47 UTC
