### ISSUE TITLE
`choices` doesn't handle nested values

### ISSUE THREAD

**Issue by smeyffret** [yargs/yargs#1365] opened 2019-06-18 20:18 UTC
```
import * as yargs from 'yargs';
const argv = yargs
    .option('app.stage', {
        choices: ['alpha', 'beta']
    })
    .argv;
```

The following script call should fail, but doesn't.
```
$ ./run.js --app.stage gamma
```

From the code, it looks like:
* [Objects.keys](https://github.com/yargs/yargs/blob/master/lib/validation.js#L130) returns `[..., 'app']` keys
* [options.choices](https://github.com/yargs/yargs/blob/master/lib/validation.js#L132) has key `'app.stage'`

which might explain the bug

---

PS: I believe the same bug affects `coerce` but I haven't investigated

**Comment by smeyffret** [comment] 2019-06-19 15:51
```
import * as yargs from 'yargs';
const argv = yargs
    .option('app-stage', {
        alias: 'app.stage',
        choices: ['alpha', 'beta']
    })
    .argv;
```
Works as expected:
```
$ ./run.js --app-stage gamma
$ ./run.js --app.stage gamma
```
both fail with the proper error message, and I can still use `argv.app.stage` in the code.

This workaround is enough for me.

**Comment by bcoe** [comment] 2019-06-25 01:16
@smeyffret we don't currently support object notation for configuring option names. So, this is more of a feature request along the lines that, inner keys on an object can't be configured.

**Comment by bcoe** [comment] 2019-06-25 01:17
duplicate of: https://github.com/yargs/yargs/issues/1230

**Comment by bcoe** [comment] 2019-06-25 01:17
please feel free to join the conversation at #1230.

**Closed by bcoe** 2019-06-25 01:17 UTC

**Comment by smeyffret** [comment] 2019-06-25 13:32
Fair enough. It might be worth making it more explicit in the doc, I couldn't find anything related to nested keys not being handled properly.

**Comment by bcoe** [comment] 2019-06-25 16:42
@smeyffret fair point, perhaps we should rework that title and continue adding to the check list. @diesal11 is adding better support for dot notation still something you'd feel passionate about?
