### ISSUE TITLE
Conflicting options with default values (or boolean values)

### ISSUE THREAD

**Issue by jordansexton** [yargs/yargs#929] opened 2017-07-28 19:52 UTC
Using `conflicts` with an option that has a default value, or a boolean option (which is automatically set to `false` even if a default value is not provided) always throws an error, because the conflicting option name will always be defined.

**Comment by john-kurkowski** [comment] 2017-08-17 22:28
Similar problem with [variadic positional arguments](https://github.com/yargs/yargs/blob/v8.0.2/docs/advanced.md#variadic-positional-arguments). Maybe because those have a default value of `[]`?

```js
yargs('my-command --update-all')
  .command('my-command [things-to-update..]', 'Some description', {
    'update-all': {
      boolean: true,
      conflicts: 'things-to-update',
    },
  }, function(argv) {
    console.log(argv['update-all']);
  })
  .argv;
```

**Expected:** log `true`.
**Actual:** exit 1, `Arguments update-all and things-to-update are mutually exclusive`.

**Comment by bcoe** [comment] 2017-09-17 20:51
@jordansexton any thoughts about what the default behavior should be ... what's weird is that `false` is a value it feels like it would be too loose to have the conflicts logic simply look for a falsy value since values like `""` would also pass the conflicts test.

**Comment by jordansexton** [comment] 2017-09-17 23:10
Yeah, special preference for `false` or falsy values would be hard to be consistent/predictable with. However, a default value shouldn't inherently conflict just by being declared. I think the expected behavior would separate the concept of a conflicting value from default values.

This might be accomplished by evaluating conflicting values that are provided as args, and then applying defaults. Alternatively, it could apply defaults/coercion/etc. and then evaluate conflicting values as being values not equal to the respective default values if provided.

```javascript
require('yargs')
    .options({
        i: {
            alias:     'include',
            default:   false,
            describe:  'Include something',
            type:      'boolean',
            conflicts: 'exclude'
        },
        e: {
            alias:     'exclude',
            default:   false,
            describe:  'Exclude something',
            type:      'boolean',
            conflicts: 'include'
        }
    });
```

I read the intent of the above option declaration is to say "either one can be true, but not both".

```shell
script                       # No args, apply defaults. No error.
script --include             # Include is true, exclude is default (false). No error.
script -i false -e false     # Superfluous, but both match their defaults. No error.
script --include --exclude   # Both aren't identical to their defaults. Error!
```

This way, `conflicts` regards default values, or provided values that match default values, as non-conflicting, satisfying the intent without a preference for a particular kind of value.

I haven't looked to see how difficult this implementation would be, but what do you think of the reasoning?

**Comment by bcoe** [comment] 2017-09-17 23:41
@jordansexton I agree with what you're saying ... I don't think the fact that we've applied a default value for an argument should result in it being flagged as a conflict.

Because the default values are applied in the parsing library `yargs-parser` and the conflicts logic is applied in yargs itself, the actual implementation might be a bit of a pain ... I think your second suggestion would work for most scenarios, if it's a value other than default it conflicts.

Do you have any interest in taking a stab at implementing this?

**Comment by jordansexton** [comment] 2017-09-17 23:43
Yeah, I'll take a look at the code and see if I can get it done.

**Comment by jordansexton** [comment] 2017-09-17 23:46
@bcoe So, defaults are applied in yargs-parser, which should be okay for what I'm thinking, provided that yargs itself can see the defaults where it would need to @ https://github.com/yargs/yargs/blob/0e0c58dd737f856ee4b3d595ddfb835247db9503/lib/validation.js#L324-L333

Can it?

**Comment by jordansexton** [comment] 2017-09-18 00:01
Okay, so it looks like https://github.com/yargs/yargs-parser/blob/00bde7d60c433c188f2529a33bab187d40645f7d/index.js#L677-L683 would need to change to include `flags.defaulted` and/or `defaults` in the returned object.

Then https://github.com/yargs/yargs/blob/0e0c58dd737f856ee4b3d595ddfb835247db9503/yargs.js#L1063-L1073 and its call location a few lines up would need to be changed to pass `argv` as well as the defaults to the code from https://github.com/yargs/yargs/issues/929#issuecomment-330102403 which can then compare against the value rather than the key.

If this sounds right to you, I'll first open a PR against yargs-parser for the first change and then follow up here.

**Comment by jordansexton** [comment] 2017-09-18 00:05
I'm considering that `Parser.detailed` should just return all the determined flags and so on, and just let the caller decide what it cares about. Treating `flags.defaults` as a special case for this feature seems weird. And then `runValidation` can be changed to a signature of `(argv, parsed, ...)` or `(argv, flags, ...)` and cherry pick aliases, defaults, and whatever else each individual `validation` method might care about.

**Comment by zzharryzz** [comment] 2017-09-28 15:28
Hey everyone. I don't know of how much use this sample will be, but it seems booleans and default values aren't the only affected types. The code below is in NodeJs, and the javascript file is called _test.js_
```JavaScript
const yargs = require('yargs');

const argv = yargs
    .usage('<cmd> args')
    .command('hello', 'the best command', {
        alias: 'h',
        describe: 'Says hello'
    }, function (argv) {
        console.log(argv);
    })
    .option('work', {
        alias: 'w',
        describe: 'does some work',
        conflicts: 'run'
    })
    .option('run', {
        alias: 'r',
        describe: 'runs something',
        conflicts: 'work'
    })
    .help()
    .argv;
```
Executing ```node test.js hello --w``` yields ```Arguments work and run are mutually exclusive```

**Comment by quilicicf** [comment] 2017-10-02 11:11
Hi I've bumped into the same issue as @zzharryzz and resorted to using the check method instead. 
I'd be willing to contribute if it helps, just tell where to look for!

**Comment by alexreg** [comment] 2017-10-12 22:09
I still get this problem on 9.0.1... it seems boolean options *always* conflict.

**Comment by quilicicf** [comment] 2017-10-14 10:31
Yup, my problem with string/integer parameters vanished with version 9 but there's still an issue with booleans. 

Check out [this code](https://github.com/quilicicf/Gut/blob/master/lib/audit.js#L6) for an example. 
I  tried adding `from-base-branch` to the list of conflicting arguments on commits number but it always results in conflicts.

**Comment by RyanZim** [comment] 2017-12-06 01:00
Just ran into this bug now.

**Comment by ljharb** [comment] 2017-12-07 06:50
I'm running into this issue as well; it makes it impossible to have mutually exclusive options where one or both are booleans.

@bcoe what I would expect is that *if* the argument is a boolean, it only considers it "set" if it's `true`. Similarly, conflicts should be checked before default values are applied.

**Comment by gombosg** [comment] 2018-03-05 12:07
Bug still confirmed for yargs 11. Options always conflict with boolean arguments (with a 'false' default value). 
Non-boolean arguments are fine.
Workaround is to disable the boolean type, often this doesn't cause any issues.
@jordansexton , did you come up with that PR?

**Comment by jordansexton** [comment] 2018-03-06 01:13
No, sorry, I haven't made any progress on this. I worked around it by just not using defaults for booleans, and then forgot to look into it beyond the comments above.

**Comment by FallingSnow** [comment] 2018-03-27 23:29
Just ran into this issue. Two options that have a default of `false` and listed as conflicting causes `Arguments encoder-preview and delete are mutually exclusive`. Setting defaults to undefined instead of false does work but it removes the `[default: false]` from the --help output.

**Comment by plroebuck** [comment] 2018-03-30 07:41
While I advocated not changing the existing setup (thinking about potential dependent package breakage issues), here's additional [discussion](https://github.com/yargs/yargs-parser/issues/116) in the yargs-parser concerning changing the default boolean to `undefined`.

**Comment by nborko** [comment] 2018-06-07 20:05
I am also running into this issue, but for type "count."  In my case, I have a "debug" count option that increases the logging level, which should conflict with a "loglevel" option that explicitly sets the logging level.  So, specifying loglevel always results in "Arguments loglevel and debug are mutually exclusive" even when debug is not specified (but has a default value of 0).

**Comment by RyanZim** [comment] 2018-07-18 20:29
This seems to be fixed in yargs v12.

**Comment by anentropic** [comment] 2019-07-23 21:11
if it was fixed in yargs 12 it is back in `13.3.0`

two boolean options with default `false` are conflicting when un-set

**Comment by bcoe** [comment] 2019-07-23 21:28
@anentropic would you be able to provide a minimal example of the bug in action, we should put a test around this if it was a regression.

**Comment by anentropic** [comment] 2019-07-23 21:32
sure, my code is basically:
```js
/**
 * @param {Array<string>} rawArgs - i.e. from `process.argv`
 * @returns {Object} parsed args
 */
export function parseArgs(rawArgs) {
  return yargs
    .command('$0 <files...>', 'My tool command', (yargs) => {
      yargs
        .option('no-color', {
          alias: 'n',
          type: 'boolean',
          default: undefined,  // default: false triggers conflict warning by yargs
          describe:
            `Monochrome output only`
        })
        .option('force-color', {
          alias: 'c',
          type: 'boolean',
          default: undefined,  // default: false triggers conflict warning by yargs
          conflicts: 'no-color',
          describe:
            `When running as a pre-commit hook we are unable to detect if the ` +
            `terminal supports colored output. If you want to see colored ` +
            `output then set this flag.`
        });
    })
    .help()
    .parse(rawArgs.slice(2))
  ;
}
```

**Comment by mleguen** [comment] 2019-08-28 17:21
This issue is solved now for booleans: a conflict will be triggered only if you explicitely set a default value (as for other types).

**Closed** 2019-11-05 05:32 UTC
Labels: Help Wanted, bug, p1, triaged
