### ISSUE TITLE
Argument Parsing with spaces?

### ISSUE THREAD

**Issue by dacbd** [yargs/yargs#2033] opened 2021-09-21 23:03 UTC
I'm not sure if is an edge case that yargs should address.

When a program is executed from a script like `bash -e /script_run_yargs_program.sh` ie GitHub actions `run:` if there are any trailing spaces after a slash on a multi-line script they get interrupted as an argument and you get a very unhelpful error message

```
Unknown argument:  
```
being akin to `printf("Unknown argument: %s" , " ")`

see: https://github.com/iterative/cml/issues/727#issuecomment-924443434 for an example

I realize this could be an unsupported edge case and Ideally people aren't putting trailing spaces after their \'s 😉

**Comment by 0x2b3bfa0** [comment] 2021-09-22 08:56
It would be nice to quote the unknown options so people can notice whitespace:

```console
Unknown argument: ' '
```

**Comment by bcoe** [comment] 2021-09-23 22:13
@DanielBarnes, I like @0x2b3bfa0's suggestion... I don't thin kit would be ridiculous to `trim` the strings we parse too, I'd have to look at the parser to see how painful this is.

**Comment by 0x2b3bfa0** [comment] 2021-09-23 22:43
Trimming the parsed strings sounds like a really unexpected behavior for some use cases. 🤔  To my mind, it should be at most a non–default [`parserConfiguration`](https://yargs.js.org/docs/#api-reference-parserconfigurationobj) option.

I can't imagine how puzzling would be if somebody tried to implement a whitespace–sensitive tool like [`tr(1)`](https://man7.org/linux/man-pages/man1/tr.1.html) and invocations like `tr --delete " "` were altered by the parser unexplainably.

**Comment by bcoe** [comment] 2021-09-24 22:20
@DanielBarnes would you be okay with @0x2b3bfa0's suggestion of quoting the error? vs., trimming.

**Comment by DanielBarnes** [comment] 2021-09-24 22:29
> @DanielBarnes would you be okay with @0x2b3bfa0's suggestion of quoting the error? vs., trimming.

Yes, I agree that quoting would be a better path. Less/no risk of introducing new behaviors to the existing API.

**Comment by jly36963** [comment] 2021-12-12 05:54
I want to work on a fix for this, but I'm having trouble reproducing this error:
```
Unknown argument:  
```

If I run a command with a space between `\` and a newline, I can reproduce this error:
```
[...] command not found
```

## Reproduction

This is how I tried to reproduce the error

### Code

```js
// multiline.js

const yargs = require('yargs')

let input

yargs(input)
  .command(
    'cmd1 [pos1]',
    'cmd1 description',
    yargs => yargs
      .option('opt1', { type: 'string' })
      .option('opt2', { type: 'string' })
      .positional('pos1', { type: 'string' }),
    argv => {
      console.log(argv)
    }
  )
  .strict()
  .parse()
```

```sh
# multiline.sh

# space after opt1 backslash
node multiline.js \
--opt1=hello \   
--opt2=world
```

### Methods

I tried the following methods:
- setting `input` to a multi-line string that has a space after the backslash
- setting `input` to undefined and calling the multiline.js file with arguments from the command line.
- setting `input` to undefined and calling multiline.js using multiline.sh (I tried with zsh, bash, and sh)

I could get the `command not found` error, but not the `unknown argument` error.

### Questions

I understand why the `command not found` error happens, as the backslash would escape the extra space and the newline wouldn't be escaped. The newline would get interpreted as the end of one command and the next line would get interpreted as the next command.

I can't figure out a way to get the `unknown arguments` error instead.

Can you help me reproduce the issue? 

(As for the solution, I'll probably go with the `Unknown argument: ' '` solution discussed above.)

**Comment by dacbd** [comment] 2021-12-12 14:52
@jly36963  put your
```
# space after opt1 backslash
node multiline.js \
--opt1=hello \   
--opt2=world
```

In a file and execute with `bash -e ./test`
As well as my the linked comment thread. Like me know if that doesn't work and I'll try help you to get something reproduces the error.

**Comment by dacbd** [comment] 2021-12-12 15:01
For context if you have a multi-line ` run: |` in GitHub actions it is executed with `bash -e` which is how I found the original error.


But if you say, copy the content of that file and paste it in your bash terminal it will see the space as the start of a new command and you get the `command not found`

**Comment by jly36963** [comment] 2021-12-12 21:34
I tried executing the `multiline.sh` file above in the following ways:
- `bash -e multiline.sh`
- `zsh -e multiline.sh`
- `sh -e multiline.sh`

All of them resulted in some output containing `command not found`.

I haven't tried it in the context of a github actions yaml file with a literal block scalar, and I'm wondering if the `unknown argument` error only happens within that context. Have you been able to reproduce the error with a bash script, or is it only in the context of a github actions `run: |` step?

(I'll try to test a github actions scenario as well)

**Comment by jly36963** [comment] 2021-12-12 23:03
I was able to reproduce -- I'll work on a fix tonight

**Comment by bcoe** [comment] 2021-12-28 23:57
@dacb, @jly36963 did some digging, and it seemed like the problem is potentially extra spaces in your bash script, after the `\`, before the `\n`.

Would you be able to confirm this?

**Closed by bcoe** 2021-12-28 23:57 UTC
Labels: feature request

**Comment by dacbd** [comment] 2021-12-29 15:47
> @dacb, @jly36963 did some digging, and it seemed like the problem is potentially extra spaces in your bash script, after the `\`, before the `\n`.
> 
> Would you be able to confirm this?

@bcoe that is correct the original error was caused by a space after the `\` but before the `\n`.
