### ISSUE TITLE
Option names with numbers incorrectly displayed in help 

### ISSUE THREAD

**Issue by ErisDS** [yargs/yargs#1332] opened 2019-04-16 14:25 UTC
If you declare an option like `v1` or `version1` the help menu outputs this incorrectly as `--v-1` or `--version-1`.

I tested this on the latest version with the following config:

```
"yargs": {
    "short-option-groups": false,
    "camel-case-expansion": false,
    "dot-notation": false,
    "parse-numbers": false,
    "boolean-negation": false
  }
```

And it was still happening.

The option works as expected. It is only the help output that is incorrect as far as I can tell.

**Comment by bcoe** [comment] 2019-04-18 01:02
@ErisDS thanks for the bug report :+1: I haven't had a ton of time to work on this library lately, so if you do have any time to dig in yourself help is greatly appreciated.

My guess would be that the bug is actually in the smaller yargs-parser dependency.

**Comment by jly36963** [comment] 2021-07-21 14:21
I want to work on a fix for this, but I'm having trouble reproducing with yargs@17.
What yargs version are you using, and does my example somewhat match your use case?

```js
yargs
  .parserConfiguration({
    "short-option-groups": false,
    "camel-case-expansion": false,
    "dot-notation": false,
    "parse-numbers": false,
    "boolean-negation": false
  })
  .command({
    command: "cmd <pos1> <pos2>",
    desc: "cmd desc",
    builder: (yargs) =>
      yargs
        .positional("pos1", {
          desc: "pos1 desc",
          type: "string",
        })
        .positional("pos2", {
          desc: "pos2 desc",
          type: "string",
        })
        .option("opt1", {
          desc: "opt1 desc",
          type: "string",
        })
        .option("v1", {
          desc: "v1 desc",
          type: "string",
        })
        .option("version1", {
          desc: "version1 desc",
          type: "string",
        }),
    handler: (argv) => {
      console.log(argv);
    },
  })
  .help()
  .parse('cmd "Hello" "World" --opt1 ":)" --help');
```

output

```
Positionals:
  pos1  pos1 desc                                            [string] [required]
  pos2  pos2 desc                                            [string] [required]

Options:
  --version   Show version number                                      [boolean]
  --help      Show help                                                [boolean]
  --opt1      opt1 desc                                                 [string]
  --v1        version1 desc                                             [string]
  --version1  version1 desc                                             [string]
```

**Comment by shadowspawn** [comment] 2023-02-26 06:14
Thanks for report @ErisDS. This wasn't easily reproducible, thanks for trying @jly36963. Perhaps it was an issue in an older version of Yargs.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2023-02-26 06:14 UTC
Labels: bug, needs-investigation
