### ISSUE TITLE
Wrong $0 in bundled electron app

### ISSUE THREAD

**Issue by acromarco** [yargs/yargs#685] opened 2016-10-20 16:52 UTC
We have an election app that is bundled to an .exe file.

A command line like
`bundled.exe -f filename`
will result in:
`
{ _: ['filename'],
  '$0': 'bundled.exe  -f' }
`

The following workaround:
`
const argv = yargs.parse(process.argv.slice(1));
`
will result in 
`
{ _: [],
 f: 'filename',
  '$0': 'bundled.exe  -f' }
`

Please notice that the $0 ist still wrong because it contains the "-f".

If this an expected behavior? Is there a way to work around it?

**Comment by zinwalin** [comment] 2017-06-23 00:13
same issue here.

**Comment by RedDeathAt614** [comment] 2018-07-16 13:50
Ditto...

**Comment by bcoe** [comment] 2019-11-10 01:22
@zinwalin @acromarco does this continue to be an issue? I wonder if we could detect we're in an electron environment and potentially handle our slicing a bit differently.

**Comment by shadowspawn** [comment] 2020-01-25 21:14
I was looking into this in weekend (in context of Commander).

References:
- https://github.com/electron/electron/issues/4690#issuecomment-217435222
- https://github.com/tj/commander.js/issues/512

Still a WIP, detection:
```
    if (process.versions && process.versions.electron) {
      parseOptions.from = 'electron';
    }
```

and decision about where to slice:
```
    case 'electron':
      if (process.defaultApp) {
        userArgs = argv.slice(2);
      } else {
        userArgs = argv.slice(1);
      }
      break;
```

**Comment by mleguen** [comment] 2020-01-29 16:35
@shadowspawn This would indeed solve the first half of this issue (`slice(1)` needed instead of `slice(2)`).

However, @acromarco also reported that it first flag (`-f`) was merged with the exe name into `req.argv[0]`.

Is is something you can reproduce too?

**Comment by shadowspawn** [comment] 2020-01-29 19:12
`-f` merged: no, I didn't investigate that aspect.

**Comment by mleguen** [comment] 2020-02-05 11:07
@shadowspawn The master branch should now be OK for your use case (ie `slice(2)`replaced by `slice(1)` if `process.defaultApp` is false). Would you please mind testing?

@zinwalin @acromarco Could one of you please give us some feedback about the 2nd point ("notice that the $0 ist still wrong because it contains the "-f") reported in the initial issue?

**Comment by shadowspawn** [comment] 2020-02-05 20:30
(Disclaimer: I do not currently use yargs or electron for real, just an interested third party!)

1) the slice issue does not appear to be fixed on master

From experimentation `process.defaultApp` is `undefined` or `true`, but not `false`. So the test for strict equality against `false` is not working as intended currently:

https://github.com/yargs/yargs/blob/a8ce12320e4dd158ab8765caf9da6f5d84d25561/lib/process-argv.js#L5

2) I am not seeing the `-f` problem. Testing on macOS.

```
console.log(process.defaultApp);
console.log(args);
const argv = require('yargs').argv;
console.log(argv);
```

```
# Calling electron directly
% ./node_modules/.bin/electron . -f filename                                                     master
true
[
  '/Users/john/Documents/Sandpits/commander/issues/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  '.',
  '-f',
  'filename'
]
{
  _: [],
  f: 'filename',
  '$0': 'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
}

# Running bundled app
% ./foo-darwin-x64/foo.app/Contents/MacOS/foo -f filename                                        master
undefined
[
  '/Users/john/Documents/Sandpits/commander/issues/electron-quick-start/foo-darwin-x64/foo.app/Contents/MacOS/foo',
  '-f',
  'filename'
]
{
  _: [ 'filename' ],
  '$0': 'foo-darwin-x64/foo.app/Contents/MacOS/foo'
}
```

**Comment by bcoe** [comment] 2020-02-05 22:21
@shadowspawn @mleguen reading the issue linked, it sounds like they were suggesting only slicing at 0 when we know the electron app is bundled, via, `process.defaultApp === false`? might be worth asking for clarification from the electron folks?

**Comment by shadowspawn** [comment] 2020-02-05 22:28
I tracked down the supporting docs:
- https://github.com/electron/electron/blob/master/docs/api/process.md#processdefaultapp-readonly

> process.defaultApp Readonly
> 
> A Boolean. When app is started by being passed as parameter to the default app, this property is true in the main process, otherwise it is undefined.

**Comment by bcoe** [comment] 2020-02-05 22:45
@zcbenz @MarshallOfSound, recommendation on how we should best detect a `argv.slice(0)` vs., `argv.slice(1)`, such that we get the bin correct?

should we be checking for `process.defaultApp === true`?

**Comment by zcbenz** [comment] 2020-02-10 00:59
@bcoe Checking `process.defaultApp` is currently the only way to handle this.

**Comment by mleguen** [comment] 2020-02-12 10:13
@shadowspawn Thanks for the tests, and pointing to the doc.

However, the doc itself isn't up to date, as in the code [`process.defaultApp` changed from a boolean to an object 17 months ago](https://github.com/electron/electron/commit/32a9df2940ced2fd2cd362190f1fe16140f05900#diff-18eb298960f17f5239f850dd8116627eL251).

So I am going to replace my `process.defaultApp === false` by `!process.defaultApp`, which will lead to:
- `slice(1)` only if `process.defaultApp` is undefined
- `slice(2)` if it is true or an object

And I will open a PR in electron to fix the doc.

**Closed** 2020-02-20 10:50 UTC
Labels: Help Wanted, enhancement, triaged

**Comment by mleguen** [comment] 2020-02-20 15:07
@shadowspawn 2nd fixed merged into master: ready for testing, if you don't mind.

**Comment by shadowspawn** [comment] 2020-02-21 21:14
Working fine now in my tests, args getting sliced at correct point.

**Comment by bcoe** [comment] 2020-03-08 00:29
@shadowspawn thanks for helping to sort this out.
