### ISSUE TITLE
Positional arguments are messed up with the default subcommand

### ISSUE THREAD

**Issue by chris-morgan** [yargs/yargs#841] opened 2017-03-28 05:53 UTC
yargs appears to be heavily designed around supporting multiple commands inside the one script. I don’t want this; I have a script with a single purpose, but with a positional argument.

Compare the following with a dummy subcommand:

```js
yargs.command('dummy <target>').args
```

An invocation of `foo.js dummy value` yields this args object:

```json
{
    "$0": "/usr/bin/nodejs foo.js",
    "_": ["foo"],
    "target": "value"
}
```

But if we change `foo` to `*`:

```js
yargs.command('* <target>').args
```

Then target is no longer filled when invoking `foo.js value`:

```json
{
    "$0": "/usr/bin/nodejs foo.js",
    "_": ["value"]
}
```

(This makes it hard to do things like put in a default value for it, as well.)

**Comment by bcoe** [comment] 2017-04-13 06:43
@chris-morgan sorry for the slow reply, have been slammed the past few weeks with work.

I agree, this behavior seems incorrect -- let's fix it to behave as expected.

**Comment by mleguen** [comment] 2019-12-18 09:15
The issue is fixed now: 

```js
yargs.command('* <target>').argv
```

when called with:

```bash
node index.js value
```

returns as expected:

```js
{ _: [], '$0': 'index.js', target: 'value' }
```

**Closed by mleguen** 2019-12-18 09:15 UTC
Labels: bug
