### ISSUE TITLE
Help stops before finishing to write in Node v6.1.0

### ISSUE THREAD

**Issue by nicola** [yargs/yargs#497] opened 2016-05-09 15:34 UTC
```js
var yargs = require('yargs')
const program = yargs
  .usage('usage: $0 [options]')

// program.option('hello', {description: 'test option'})
for (var i = 0; i < 20; i++) {
  program.option('hello_' + i, {description: 'this is a medium sized description, good!'})
}

program
  .help('help')
  .wrap(null)

const argv = program.argv

if (argv._.length < 1) {
  yargs.showHelp()
}
```

Here is my little command:

```
$ node example2.js
usage: example2.js [options]

Options:
  --hello_0   this is a medium sized description, good!
  --hello_1   this is a medium sized description, good!
  --hello_2   this is a medium sized description, good!
  --hello_3   this is a medium sized description, good!
  --hello_4   this is a medium sized description, good!
  --hello_5   this is a medium sized description, good!
  --hello_6   this is a medium sized description, good!
  --hello_7   this is a medium sized description, good!
  --hello_8   this is a medium sized description, good!
  --hello_9   this is a medium sized description, good!
  --hello_10  this is a medium sized description, good!
  --hello_11  this is a medium sized description, good!
  --hello_12  this is a medium sized description, good!
  --hello_13  this is a medium sized description, good!
  --hello_14  this is a medium sized description, good!
  --hello_15  this is a medium sized description, good!
  --hello_16  this is a medium sized description, good!
  --hello_17  this is a medium sized description, good!
  --hello_18  this is a medium sized description, good!
  --hello_19  this is a medium sized description, good!
  --help      Show help  [boolean]
```

All correct, but when I use the flag `--help`, it breaks:

```
$ node example2.js --help
usage: example2.js [options]

Options:
  --hello_0   this is a medium sized description, good!
  --hello_1   this is a medium sized description, good!
  --hello_2   this is a medium sized description, good!
  --hello_3   this is a medium sized description, good!
  --hello_4   this is a medium sized description, good!
  --hello_5   this is a medium sized description, good!
  --hello_6   this is a medium sized description, good!
  --hello_7   this is a medium sized description, good!
  --hello_8   this is a medium sized description, good!
  --hello_9   this is a medium sized description, good!
  --hello_10  this is a medium sized description, good!
  --hello_11  this is a medium sized description, good!
  --hello_12  this is a medium sized description, good!
  --hello_13  this is a medium sized description, good!
  --hello_14  this is a medium sized description, good!
  --hello_15  this is a medium sized description, good!
  --hello_16  this is a medium sized description, good!
  --hello_17 %
```

This is the same problem facing https://github.com/tj/commander.js/issues/530 right now,
do you have a fix for this planned?

**Comment by bcoe** [comment] 2016-05-09 17:24
@nicola interesting, is there a chance that printing the output is taking more than one tick? this would be strange behavior, but should be fixable; looks like we might need to do some thorough testing debugging on Node@6.x.

**Comment by nicola** [comment] 2016-05-09 17:25
hey @bcoe thanks for your quick reply, Node v6 has done several updates to Buffer, worth looking into it

**Comment by lpinca** [comment] 2016-05-10 12:18
Posting this here for reference: https://github.com/nodejs/node/issues/6456.

**Comment by eljefedelrodeodeljefe** [comment] 2016-05-10 17:15
`console.log` is not blocking for a while now. We are seeing lots of behaviour like this in similar cases and repos, because recent `libuv` changes have made this problem visible. We are working on workarounds in node core.

The problem often arises when looping over `stdout` or `console` in combination with with `process.on('exit', handlers)`, this could be an immediate fix. I keep you posted.

**Comment by bcoe** [comment] 2016-05-10 17:51
@nicola @eljefedelrodeodeljefe I've been chatting with @othiym23, and have a plan of action for a hacky patch; @nicola could you submit a failing test case in `test/integration`?

**Comment by eljefedelrodeodeljefe** [comment] 2016-05-10 18:01
Just to throw in some: I assume it's about the recursive call of parseArgs and the process.exit(0) [here](https://github.com/yargs/yargs/blob/74fcfbc34a8094943f9c397ed922cec7dfbb2416/yargs.js#L684).

At best the hotfix is revertable in the future though. The private process APIs are likely to change and are a terrible hack - if you consider them.

**Comment by eljefedelrodeodeljefe** [comment] 2016-05-10 18:24
I have tried replacing all the process.exit() with 

```js
ee.on('custom_exit', function () {
  // no-op
})
```
and a respective `ee.emit('custom_exit', 0)` and at least that prints everything. You would have to decide whether that is breaking the APIs

**Comment by eljefedelrodeodeljefe** [comment] 2016-05-10 18:56
Exploring this here https://github.com/yargs/yargs/pull/498

**Comment by bcoe** [comment] 2016-05-10 19:08
@eljefedelrodeodeljefe would `custom_exit` be emitted immediately, or would the consumer code be able to execute in the current `tick` before our event fires; something we should test :)

**Comment by eljefedelrodeodeljefe** [comment] 2016-05-10 21:19
hmm. Can you think of a test case? When I see this right node core defer most events to the nextTick. In this case I would suppose it wouldn't matter because when you return from top scope and there is still something on the event loop that will execute. But, tbh, I am not sure.

**Comment by bcoe** [comment] 2016-05-15 03:38
@nicola please give this a spin:

`npm i yargs@next`

I've written this shim: https://github.com/yargs/set-blocking

**Comment by bcoe** [comment] 2016-05-16 18:49
@nicola bump; somewhat worried about this change, so would love to have the second set of eyes before it gets promoted to `latest`.

**Comment by nexdrew** [comment] 2016-05-16 19:07
@bcoe FWIW, using @nicola's script and running with `--help` on Node 6.1.0, I was able to consistently see the problem with `yargs@4.7.0` and cannot reproduce the problem with `yargs@4.7.1`, so it looks good to me. 👍

**Comment by bcoe** [comment] 2016-05-17 04:02
@nicola this should now be fixed on `latest`.

**Comment by nicola** [comment] 2016-05-17 19:38
It fails in 4.7.1 :(

**Comment by bcoe** [comment] 2016-05-17 20:14
@nicola awesome, I can close this out?

**Closed by bcoe** 2016-05-17 20:14 UTC
