### ISSUE TITLE
exception thrown when yargs.parsed.newAliases is undefined

### ISSUE THREAD

**Issue by oscarocornejo** [yargs/yargs#1144] opened 2018-06-06 03:45 UTC
Found something of an issue when using `yargs.showHelp()`
[L761](https://github.com/yargs/yargs/blob/master/yargs.js#L761)

it seems that when `self._parseArgs(processArgs)` is called, it is not saving the results to `self.parsed`

if you put a breakpoint on this line: [L1012](https://github.com/yargs/yargs/blob/master/yargs.js#L1012), you will see that the `self.parsed` property contains the appropriate items.

however, after this function is done, on [L762](https://github.com/yargs/yargs/blob/master/yargs.js#L762),
`self.parsed` is set back to `false` instead of an object. this leads to their being a parse error:

`TypeError: Cannot convert undefined or null to object`
`.concat(Object.keys(yargs.parsed.newAliases) || [])`

under function: `usage.showHelp(` [L240](https://github.com/yargs/yargs/blob/master/lib/usage.js#L240)

Thanks! 👍

**Comment by mleguen** [comment] 2019-06-19 08:06
I just ran into this when trying to answer @varl 's question in #1137.

The problem is not parsed being overwritten, but the returned value of require("yargs") having its properties (not its functions) frozen at their inital value (false for parsed).

So:

```js
const yargs = require("yargs")
yargs.parse()
console.log(yargs.parsed)
```

returns false, whereas:

```js
const yargs = require("yargs")
y = yargs.parse()
console.log(y)
```

returns the expected parsed object.

This is due to the way singletonify() in index.js is written.

I'll try to correct this behavior.

**Comment by mleguen** [comment] 2019-06-26 07:06
I am unable to reproduce the issue, so I was probably wrong when thinking it was related to `require("yargs")` properties being frozen.

@oscarocornejo I know it's been a while, but could you please give us some sample code reproducing the issue?

**Comment by bcoe** [comment] 2019-07-30 05:42
@oscarocornejo, with @mleguen's work investigating this issue, I ultimately opted to deprecated accessing `yargs.parsed`, which has issues when used in conjunction with commands (which require tracking state across multiple invocations of the parser).

Do you think you can instead use `yargs.parse()` or `yargs.argv`'s return value?

**Comment by oscarocornejo** [comment] 2019-08-10 04:28
That should be fine, thanks guys 👍

**Comment by mleguen** [comment] 2019-08-14 13:07
Closing, as `self.parsed` is officially no longer supported since 14.0.0.

**Comment by gajus** [comment] 2019-08-21 22:20
I am seemingly getting the same error in ^14.0.0.

I don't have much to share other than this is how I intialize the code:

```js
yargs
  .env('ADM')
  .commandDir('commands')
  .help()
  .wrap(80)
  .parse();

```

This is the error that I get:

```js
(node:92950) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.help (/Users/gajus/Documents/dev/applaudience/data-manager/node_modules/yargs/lib/usage.js:240:22)
    at Object.self.showHelp (/Users/gajus/Documents/dev/applaudience/data-manager/node_modules/yargs/lib/usage.js:432:15)
    at Object.Yargs.self.showHelp (/Users/gajus/Documents/dev/applaudience/data-manager/node_modules/yargs/yargs.js:790:11)
    at Object.fail (/Users/gajus/Documents/dev/applaudience/data-manager/node_modules/yargs/lib/usage.js:50:17)
    at /Users/gajus/Documents/dev/applaudience/data-manager/node_modules/yargs/lib/command.js:239:36
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

**Comment by gajus** [comment] 2019-08-21 22:30
https://github.com/yargs/yargs/blob/8792d13445458c51bdff6612b1edda5aa344b6a0/lib/usage.js#L240

Here `yargs.parsed.newAliases` is `undefined`.

**Comment by gajus** [comment] 2019-08-21 22:32
My `builder` is simply:

```js
export const builder = (yargs: Object): void => {
  yargs
    .options({
      'cinema-data-scraper-sources-path': {
        demand: true,
        description: 'Path to the directory that includes the cinema data scraper sources.',
        type: 'string',
      },
      // [..]
    });
};

```

**Comment by bcoe** [comment] 2019-08-22 00:44
@gajus mind opening a new issue calling out this specific error?

**Comment by bcoe** [comment] 2019-08-22 00:55
@gajus actually, I went ahead and reopened this issue with a new title :+1:

Can you figure out a reproduction that doesn't involve a command directory?

```js
require('./')
  .env('ADM')
  .command('my-cool-command', 'description', (yargs) => {
  yargs
    .options({
      'cinema-data-scraper-sources-path': {
        demand: true,
        description: 'Path to the directory that includes the cinema data scraper sources.',
        type: 'string',
      },
      // [..]
    });
  }, () => {})
  .help()
  .wrap(80)
  .parse();
```

:point_up_2: the above works correctly for me.

**Comment by gajus** [comment] 2019-08-22 01:24
I have tried a bunch of cases and I cannot replicate this without using command directory.

**Comment by gajus** [comment] 2019-08-22 01:25
Will give it a try tomorrow again.

**Comment by gajus** [comment] 2019-08-22 13:38
I cannot replicate it in a single file, but with commands it is easy:

```js
// ./bin.js
require('yargs')
  .commandDir('commands')
  .parse();

```

```js
// ./commands/foo.js
module.exports = {
  command: 'foo',
  desc: '',
  builder: () => {},
  handler: async () => {
    throw new Error('test');
  }
};

```

```
(node:23038) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.help (/Users/gajus/Documents/dev/temp3/node_modules/yargs/lib/usage.js:240:22)
    at Object.self.showHelp (/Users/gajus/Documents/dev/temp3/node_modules/yargs/lib/usage.js:432:15)
    at Object.Yargs.self.showHelp (/Users/gajus/Documents/dev/temp3/node_modules/yargs/yargs.js:790:11)
    at Object.fail (/Users/gajus/Documents/dev/temp3/node_modules/yargs/lib/usage.js:50:17)
    at /Users/gajus/Documents/dev/temp3/node_modules/yargs/lib/command.js:239:36
(node:23038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by bcoe** [comment] 2019-08-23 18:32
@gajus you're not using using TypeScript are you? I found a bug that throws similar errors to yours, that happens as a result of:

```
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
const yargs = __importStar(require("yargs"));
```

The `__importStar` helper in TypeScript executes all the methods on yargs, which in turn seems to put the parser in a strange state. Any thoughts @mleguen? I'm wondering if this could be the root cause of some of the issues we're seeing.

**Comment by gajus** [comment] 2019-08-23 18:57
I am not using TypeScript.

**Comment by gajus** [comment] 2019-08-23 18:58
What is the problem with this test case?

https://github.com/yargs/yargs/issues/1144#issuecomment-523910162

**Comment by bcoe** [comment] 2019-08-23 19:51
@gajus test case should be fine, haven't dug into it too much yet; was just wondering if something similar is being caused by your example, i.e., all the fields being walked on an yargs instance (will need to dig and see).

**Closed** 2019-09-04 08:51 UTC
Labels: p0
