### ISSUE TITLE
`implies` behaves incorrectly on boolean options

### ISSUE THREAD

**Issue by getchardy** [yargs/yargs#2372] opened 2023-11-02 17:07 UTC
As of `17.1.0`, the behavior of `implies` on a boolean option is incorrect.

```
// test.js

const yargs = require('yargs')

const argv = yargs
  .options({
    boolFlag: {
      type: 'boolean',
      default: false,
      implies: ['otherArg'],
    },
    otherArg: {
      type: 'string',
    },
  })
  .help()
  .parseSync()

console.log(argv)
```

On `17.1.0` running the script without the boolFlag gives the following:
```
> node test.js
test

test command

Options:
  --version   Show version number                                      [boolean]
  --help      Show help                                                [boolean]
  --boolFlag                                          [boolean] [default: false]
  --otherArg                                                            [string]

Missing dependent arguments:
 boolFlag -> otherArg
```

On `17.0.0` running the script without the boolFlag gives the following which is what I believe is correct:
```
>  node test.js 
{ _: [], boolFlag: false, 'bool-flag': false, '$0': 'test.js' }
{ _: [], boolFlag: false, 'bool-flag': false, '$0': 'test.js' }
```

I think this is the PR where the defect was introduced: https://github.com/yargs/yargs/pull/1985

**Comment by shadowspawn** [comment] 2023-11-03 22:37
Thanks for the clear example code and usage.

The 17.1.0 behaviour is as intended. Default values are not treated specially here and since they set the option key, the implied option must also be set. The PR makes the behaviour consistent based on whether the option is set rather than depending on the option value.

> Given the key x is set, it is required that the key y is set.

https://yargs.js.org/docs/#api-reference-impliesx-y

**Comment by getchardy** [comment] 2023-11-07 00:35
Thanks for the info and good explanation about the default.

I think I need to adjust my mindset as to how this applies to boolean values, can you please confirm if I'm on the right wavelength now?

Before: "setting a flag X to true can make some additional arguments mandatory"
Now: "X and its related options must all be set, or not set at all"

Is there anything else in the API that supports conditionally mandatory arguments? Otherwise I'll just manually validate.

**Comment by shadowspawn** [comment] 2023-11-07 05:49
> Now: "X and its related options must all be set, or not set at all"

To be clear, you can set the implied option (`otherArg` in your example) without needing to set X (`boolFlag` in your example).

> Is there anything else in the API that supports conditionally mandatory arguments? 

No. You may get most of what you want if you simply omit the default value for `boolFlag`.

However, `--no-boolFlag` will trigger the implied mandatory arguments too. To get conditional mandatory arguments based on whether the option is true rather than just being set, manually validate.

**Comment by shadowspawn** [comment] 2023-12-16 23:20
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2023-12-16 23:20 UTC
