### ISSUE TITLE
404 on docs page of website

### ISSUE THREAD

**Issue by brmenchl** [yargs/yargs#897] opened 2017-06-12 23:56 UTC
I was on the site a couple of hours ago, I suspect it has to do with the most recent commit 30a1872.

**Comment by bcoe** [comment] 2017-06-12 23:57
@brmenchl this will be fixed in a couple hours; the problem is that the CDN that backs the website caches content for four hours.

**Comment by bcoe** [comment] 2017-07-05 00:09
this should now be fixed.

**Closed by bcoe** 2017-07-05 00:09 UTC
