### ISSUE TITLE
`repeat` argument is treated special when using `unknown-options-as-args`

### ISSUE THREAD

**Issue by johanblumenberg-symphony** [yargs/yargs#1489] opened 2019-11-21 22:28 UTC
For some reason, `repeat` argument is treated special.

```js
var yargs = require('yargs');
var assert = require('assert');

let args = yargs
    .parserConfiguration({
        'unknown-options-as-args': true
    })
    .option('known', { type: 'string' })
    .argv;

console.log('known:', args.known);
console.log('repeat:', args.repeat);
console.log('_:', args._);
    
assert.equal(args.known, 'x');
assert.equal(args.repeat, undefined);
assert.deepEqual(args._, [ '--repeat', '100', '--unknown', '200']);
```

Run as:

```
$ node index.js --known x --repeat 100 --unknown 200
```

The output is:

```
known: x
repeat: 100
_: [ '--unknown', '200' ]
```

I did not add any option named `repeat`, so I would expect this argument to end up in `_`.
However, it shows up as a named option, as if I had defined an option named `repeat`, or if I didn't use `unknown-options-as-args`.

Other unknown options are correctly put in `_`.

**Comment by mleguen** [comment] 2019-12-04 14:48
I can reproduce the issue with the example given by @johanblumenberg-symphony

**Comment by mleguen** [comment] 2019-12-04 14:55
The bug is in yargs-parser.

**Comment by mleguen** [comment] 2019-12-04 17:56
yargs/yargs-parser#227 submitted to fix this issue.

In short: `repeat` has a special treatment because it is the name of a method of String.prototype.

**Comment by mleguen** [comment] 2020-02-12 16:39
@johanblumenberg-symphony This bug was fixed upstream in yargs-parser, and the fix is now in yargs' master branch:
```bash
$ node index.js --known x --repeat 100 --unknown 200
known: x
repeat: undefined
_: [ '--repeat', '100', '--unknown', '200' ]
```

Could you please confirm this is OK for you when using master branch?

**Comment by shadowspawn** [comment] 2023-02-25 08:27
Thanks for the report. An answer was provided (a fix thanks to @mleguen), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2023-02-25 08:27 UTC
Labels: bug
