### ISSUE TITLE
Array doesn't expand as .env var

### ISSUE THREAD

**Issue by laggingreflex** [yargs/yargs#1199] opened 2018-08-15 13:36 UTC
Have a config like `.options({a: {type: 'array'}}).env()`

And env var `A=1 2`

* Expected: `argv.a = [1, 2]`

* Actual: `argv.a = '1 2'`

**Comment by alFReD-NSH** [comment] 2019-11-14 18:19
This  seems to be a duplicate of #821

**Closed** 2019-11-14 23:16 UTC
