### ISSUE TITLE
[bug] command option's choises is of type unknown

### ISSUE THREAD

**Issue by its-dibo** [yargs/yargs#2397] opened 2024-04-08 02:33 UTC
```
let args  = yargs()
 .command('example', '...', {
   test:{
     choices: ["a", "b"] as const;
   }
})
.parseSync()

//<------- error: Argument of type 'unknown' is not assignable to parameter of type '"a" | "b"'.ts(2345)
test(args._[0].test)

function test(value: 'a' | 'b'){}
```

**Comment by shadowspawn** [comment] 2024-04-08 08:26
I was not able to reproduce this problem. I created a new package and initialised the TypeScript configuration with `npx tsc --init`.

```ts
import yargsFactory from 'yargs/yargs';

const argv  = yargsFactory(process.argv.slice(2))
 .command('example', '...', {
   test:{
     choices: ["a", "b"] as const
   }
})
.parseSync();

console.log(argv);
```

```console
% node ts.js example --test  
ts.js example

...

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --test                                                     [choices: "a", "b"]

Invalid values:
  Argument: test, Given: true, Choices: "a", "b"
```

**Comment by its-dibo** [comment] 2024-04-09 19:50
> ```
> % node ts.js example --test 
> ```

this is not the issue, yargs itself can detect the user's input.
but the issue is that there is no way to tell typescript the correct type, you need to always cast each arg before using it

**To reproduce the issue:**
1- starting from your snippet, add a single line `argv.test`
2- hover over `argv.test` to see its type. it should be something like `a | b`, but instead it is just `unknown`

**Comment by shadowspawn** [comment] 2024-04-09 20:32
(I misunderstood the issue. Thanks for explaining. I will have another look.)

**Comment by shadowspawn** [comment] 2024-04-12 00:22
Here is a way of defining the command that gets the choices into the types.

```ts
import yargsFactory from 'yargs/yargs';

const yargs = yargsFactory(process.argv.slice(2))
  .command('example [test]', '...',
    (yargs) => {
      return yargs.positional('test', {
        type: 'string',
        choices: ["a", "b"] as const
      });
    },
    (argv) => {
      console.log(argv);
      const inspect = argv.test; // <-- "a" | "b" | undefined
    });

yargs.parseSync();
```

**Comment by shadowspawn** [comment] 2024-10-19 20:15
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2024-10-19 20:15 UTC
Labels: question, typescript, DefinitelyTyped
