### ISSUE TITLE
commandDir does not automatically exit the process after handler is executed

### ISSUE THREAD

**Issue by nanianlisao** [yargs/yargs#2374] opened 2023-11-16 09:31 UTC
I encountered a problem when using the commandDir method of yargs. I found that even if the handler function has been executed, yargs does not automatically exit the process. This is inconsistent with the behavior of the command method, which automatically exits the process after the handler function is executed.

Here is the code snippet where I encountered the problem:
```js
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
yargs(hideBin(process.argv))
  .scriptName('xxx')
  .commandDir('./commands')
  .help()
  .version()
  .parse();
```
and `commands/test.js` code is as follows
```js
export const command = 'test';
export const describe = 'test demo';
export const builder = (_yargs) => {};
export const handler = (argv) => {
  console.log('argv-', argv);
};

export const exitProcess = true;
```

When I execute the test command, the process will not exit。

I expect the commandDir method to automatically exit the process after the handler function is executed, just like the command method. Is this a bug, or is my understanding of yargs incorrect? 

Looking forward to your reply

**Comment by shadowspawn** [comment] 2023-11-20 06:32
> This is inconsistent with the behavior of the command method, which automatically exits the process after the handler function is executed.

I am not seeing the behaviour you describe for the command method. I tried a simple command and the code falls through after calling the handler. There might be something else in your program or the command-line arguments that is causing it to exit?

```js
const yargs = require('yargs/yargs');

yargs(process.argv.slice(2))
  .command(
    'sub',
    'sub description',
    function (y) { return y; },
    function (argv) { console.log('Called sub'); }
  )
  .parse();

console.log('After parse');
```

```console
% node command.js sub
Called sub
After parse
```

**Comment by shadowspawn** [comment] 2023-11-20 06:33
(I am guessing your example code is TypeScript, since `commandDir` is not supported for esm.)

**Comment by nanianlisao** [comment] 2023-11-20 06:47
Perhaps my expression is not clear enough。

in my example.

```
export const handler = (argv) => {
  console.log('argv-', argv);
};
```

At this point, the handler can be triggered normally and print the content of argv. But after the handler is executed, the process does not exit directly. This confuses me.

> (I am guessing your example code snippet is TypeScript, since `commandDir` is not supported for esm.)

In addition, although I used esm in my example code, in the actual scenario, I transpiled it to cjs.

> I tried a simple command and the code falls through after calling the handler.

it should be noted that I found that `command` does not have this issue. The problematic one is `commandDir`.

**Comment by shadowspawn** [comment] 2023-11-20 07:07
I reproduced the behaviour you describe with `.commandDir()`. The process does not automatically exit after calling the handler.

But I am seeing the _same_ behaviour with `.command()`. The process does not automatically  exit after calling the handler.

**Comment by nanianlisao** [comment] 2023-11-20 07:14
https://stackblitz.com/edit/stackblitz-starters-jvkcat?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=pnpm-workspace.yaml,packages%2Fcli%2Fbin%2Findex.js,packages%2Fcli%2Fpackage.json,package.json,packages%2Fexample%2Fpackage.json,packages%2Fcli%2Findex.js,packages%2Fcli%2Fcommands%2Ftest.js&title=node.new%20Starter
I have created a demo and found that both of them can exit normally, but they behave differently in my real project.

Perhaps there are other factors affecting it, and I will investigate later.

I'm sorry if I have wasted your valuable time.

**Comment by shadowspawn** [comment] 2023-11-21 19:51
Currently not looking like a bug. I suspect other code in your real project, but the difference might still be Yargs and triggered by using some other Yargs feature. Good luck tracking down the next clue.

**Comment by shadowspawn** [comment] 2023-12-16 23:18
No further activity in a month. Closing this as probably not a Yargs issue as such.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2023-12-16 23:18 UTC
