### ISSUE TITLE
can't import yargs/helpers in esm-shimmed environment

### ISSUE THREAD

**Issue by ixis-doug** [yargs/yargs#1798] opened 2020-11-05 20:49 UTC
`import { hideBin } from 'yargs/helpers'` fails when invoking like `node -r esm index.js`

The esm module is a production-quality ESM loader and works with old versions of node (and current versions) without any funny configuration required (like setting `"type": "module"` in package.json).

The following error is printed:
```
/home/foobar/my-project/node_modules/yargs/build/lib/utils/apply-extends.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/foobar/my-project/node_modules/yargs/build/lib/utils/apply-extends.js
require() of ES modules is not supported.
require() of /home/foobar/my-project/node_modules/yargs/build/lib/utils/apply-extends.js from /home/foobar/my-project/node_modules/yargs/helpers.mjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.  Instead rename apply-extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/foobar/my-project/node_modules/yargs/package.json
```

tested yargs 16.1.0 on node 12.16 and 12.19 with esm 3.2.25

**Comment by ljharb** [comment] 2020-11-09 00:39
Duplicate of #1789.

**Closed** 2020-11-13 15:25 UTC

**Comment by bcoe** [comment] 2020-11-15 18:44
@ixis-doug let me know if `yargs@16.1.1` does the trick for you.
