### ISSUE TITLE
yargs shows CLI name for each command

### ISSUE THREAD

**Issue by trivikr** [yargs/yargs#2329] opened 2023-05-02 14:51 UTC
## Describe the bug
yargs shows CLI name for each command

## Steps to reproduce
Run the following code with `yargs@17.7.2`:

```js
// index.mjs
import yargs from "yargs/yargs";
import { hideBin } from "yargs/helpers";

yargs(hideBin(process.argv))
  .command(
    "get",
    "make a get HTTP request",
    (yargs) => {},
    (argv) => {}
  )
  .help().argv;
```

```console
$ node index.mjs --help
```

#### Observed behavior
The CLI `index.mjs` is added in the description of command which is redundant

```console
index.mjs [command]

Commands:
  index.mjs get  make a get HTTP request

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

#### Expected behavior
The redundant CLI `index.mjs` is not added in the each command description, as it take space

```console
index.mjs [command]

Commands:
  get  make a get HTTP request

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

**Comment by trivikr** [comment] 2023-05-02 14:59
Resolving as this is working as designed.

From yargs docs [.scriptName($0)](https://yargs.js.org/docs/#api-reference-scriptname0):
> Set the name of your script ($0). Default is the base filename executed by node (`process.argv[1]` or `process.argv[0]` for built electron apps)

User can always set their own script name.

```js
// ...

yargs(hideBin(process.argv))
  .usage("Usage: long-cli-name <command> [options]")
  .scriptName("")
// ...
```

```console
$ node index.mjs --help
Usage: long-cli-name <command> [options]

Commands:
  get  make a get HTTP request

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

**Comment by shadowspawn** [comment] 2023-05-03 05:36
When you are just running the script using node, that first name is the script name and not very useful. When your command is being used directly and you see the name of the command you are running, it makes more sense.

**Comment by shadowspawn** [comment] 2023-05-03 20:53
I made it sound like it was "wrong" when I said "not very useful". That was stronger than I intended! I could perhaps have said "less obvious".

I'll have another think about the reasons for the behaviour and whether it still make good enough sense.

---

The current behaviour is by design. The intention is to show the chain of command and subcommands you would type on the command-line

```console
% npm publish --help 
...
Usage:
npm publish <package-spec>
...

% git clone --help
...
SYNOPSIS
       git clone [--template=<template-directory>]
...
```

On Unix systems, the script name may actually be the same as the command name if the script includes a "shebang" so it is runnable:
```
#!/usr/bin/env node
```

However, times are changing. The file suffix is significant now for the distinction between CommonJS (`.cjs`) and ESM (`.mjs`) so less likely the filename is the command name.

**Comment by trivikr** [comment] 2023-05-03 21:37
> The intention is to show the chain of command and subcommands you would type on the command-line

npm does show chain of command and subcommands
```console
$ npm --help | head
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
```

But git doesn't
```console
$ git --help | head -n 18
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index
```

Are there some CLIs which should be considered as standard behavior, to come up with a decision?

**Comment by shadowspawn** [comment] 2023-05-03 21:46
Oh, I just paid more attention to your original comment. I missed you were seeing this in the "Commands:" section rather than the usage. I didn't pay close attention because it had been closed!

I suspect it was done on purpose, but will track down the details. I'll reopen in meantime.

**Comment by shadowspawn** [comment] 2023-05-03 21:53
> Are there some CLIs which should be considered as standard behavior, to come up with a decision?

I personally usually check git and npm and Commander for reference, but I don't consider them as standard as such.

**Comment by shadowspawn** [comment] 2023-05-04 07:06
The current behaviour was added in: https://github.com/yargs/yargs/pull/990

**Comment by shadowspawn** [comment] 2023-05-04 07:28
> npm does show chain of command and subcommands

That is in the usage, which is different from a list of commands which are available.

Npm is bit special! I found in the long help, the commands were not prefixed in list, but are prefixed in the usage.

```
% npm help --long  
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
...

All commands:

    access          Set access level on published packages
                    
                    Usage:
                    npm access list packages [<user>|<scope>|<scope:team> [<package>]

```

**Comment by shadowspawn** [comment] 2023-07-16 23:01
Closing in favour of earlier #1964

**Closed by shadowspawn** 2023-07-16 23:01 UTC
