### ISSUE TITLE
conflicts problem

### ISSUE THREAD

**Issue by u9g** [yargs/yargs#1910] opened 2021-04-09 03:47 UTC
I tried conflicts but if I add it to an option then start the program it always stops and says arguments x and y are mutually exclusive even if they aren't used at once

**Comment by bcoe** [comment] 2021-04-11 02:04
@u9g could you provide some code that demonstrates the bug you're running into?

**Comment by u9g** [comment] 2021-04-11 02:23
> @u9g could you provide some code that demonstrates the bug you're running into?

Sure

```js
const path = require('path')

const argv = require('yargs/yargs')(process.argv.slice(2))
  .usage('Usage: $0 [options]')
  .option('version', {
    alias: ['v', 'ver'],
    string: true,
    demandOption: true
  })
  .option('outputFolder', {
    alias: ['o', 'output'],
    default: 'output',
    string: true,
    coerce: path.resolve,
    conflicts: 'dryrun'
  })
  .option('h', {
    alias: 'help',
    description: 'Display help message'
  })
  .option('dryrun', {
    alias: 'd',
    default: false,
    boolean: true
  })
  .showHelpOnFail(false, 'whoops, something went wrong! get more info with --help')
  .argv

console.log(argv)
```

run: `node .\index.js -v 1.1`

**Comment by Celthi** [comment] 2021-04-20 23:44
I had the same problem so I debug the code. I think the bug is in the following line
https://github.com/yargs/yargs/blob/395bb67749787d269cabe80ffc3133c2f6958aeb/lib/validation.ts#L391
The above code check if the argument is undefined but actually we should still check if it is `false` or `true`.

**Comment by Celthi** [comment] 2021-04-27 07:05
@bcoe I have found the suspected bug above, could you review it? I can make a PR if we agree on the fix.

**Comment by dsl101** [comment] 2021-06-14 15:27
I'm getting a very similar problem, and I don't know how much it's related to #929 which was marked as fixed a long time ago. Here's a trivial example which will throw mutually exclusive warnings, no matter what:
```
const options = require('yargs')
  .options({
    'limit': {
      describe: 'Limit to specified number of lines',
      default: 10,
      conflicts: 'all',
    },
    'all': {
      describe: 'Show all lines',
      default: false,
      conflicts: 'limit',
    }
  })
  .argv

node test.js
node test.js --all
node test.js --limit 5
```
Removing the default value for `--all` allows `--limit` to be used, but still throws an error if you try to use `--all`

**Comment by dsl101** [comment] 2021-06-15 11:20
And here's an example using _only_ booleans that seems like it's such a common use case I must be doing something wrong. I have 2 'flags' to pass (`--some` or `--all`) which are mutually exclusive, and if nothing is passed, the default should be `--some`:
```
const options = require('yargs')
  .options({
    'all': {
      describe: 'Show all lines',
      type: 'boolean',
      conflicts: 'some',
    },
    'some': {
      describe: 'Show some lines',
      type: 'boolean',
      default: true,
      conflicts: 'all',
    }
  })
  .argv
```
With this setup, it's not possible to specify `--all` without getting the conflict error. I'm not sure if there's an official way to get the version number from the library, but package.json says 17.0.1.

**Comment by bcoe** [comment] 2021-06-25 22:00
@Celthi apologies for the slow response, my open source time is limited these days.

If you're still interested in landing a fix, please do go ahead and submit a PR 😄 always appreciated.

**Comment by jly36963** [comment] 2021-07-14 04:33
@u9g
@dsl101 

I believe conflicts is working as intended. In the examples provided, I noticed the following:
- two options
- those options are conflicting
- both have a default value, which means that both will always have a value.

The conflicting validation logic checks that if two options are conflicting, that at least one of them is undefined in the argv object. The validation will always fail if defaults are set for both conflicting options.

I don't think there is currently a way to do what you're trying to do, without moving either the default logic or conflicts logic to the handler.

```js
// using .command(cmd, desc, builder, handler)

const argv = yargs
  .command(
    // cmd
    "$0", // * or $0 specify this as the default command
    // desc
    "cmd description",
    // builder
    yargs => yargs
      .option('version', {
        alias: ['v', 'ver'],
        string: true,
        demandOption: true
      })
      .option('outputFolder', {
        alias: ['o', 'output'],
        // default: 'output',
        string: true,
        conflicts: 'dryrun'
      })
      .option('dryrun', {
        alias: 'd',
        // default: false,
        boolean: true
      })
      .option('h', {
        alias: 'help',
        description: 'Display help message'
      })
      .showHelpOnFail(false, 'whoops, something went wrong! get more info with --help'),
    // handler
    argv => {
      let { dryrun = false, outputFolder = 'output' } = argv
      if (dryrun) {
        console.log(`dryrun: ${dryRun}`)
        return
      }
      console.log(`outputFolder: ${outputFolder}`)
    }
  ).parse('-v 1.1')

  console.log(argv)

// using .command(module)

const argv = yargs('-v 1.1')
.command({
  command: "$0", // * or $0 specify this as the default command
  desc: "cmd description",
  builder: {
    version: {
      alias: ['v', 'ver'],
      string: true,
      demandOption: true
    },
    outputFolder: {
      alias: ['o', 'output'],
      // default: 'output',
      string: true,
      conflicts: 'dryrun'
    }, 
    dryrun: {
      alias: 'd',
      // default: false,
      boolean: true
    },
    help: {
      alias: 'h',
      description: 'Display help message'
    }
  },
  handler: argv => {
    let { dryrun = false, outputFolder = 'output' } = argv
    if (dryrun) {
      console.log(`dryrun: ${dryRun}`)
      return
    }
    console.log(`outputFolder: ${outputFolder}`)
  }
}
).parse()

console.log(argv)
```

@bcoe If there is a change in existing behavior or a new feature to add, I'm down to work on it.

**Comment by dsl101** [comment] 2021-07-15 14:16
I think the case where you want to prevent the user _specifying_ more than one thing, but them both having some in-built default value is pretty common, and what most people (including me) are trying to do when they get stuck. But, appreciate this could be seen as a breaking change if the handling of conflicts was changed to accommodate that. 

IMO, having default values should not be included when checking for conflicts—in that, most of the time, what you're trying to prevent is the _user_ specifying 2 things, rather than the source code author specifying 2 things. 

Perhaps resolving this via introducing a new setting `mutex` might be the simplest approach? E.g.:
```
const options = require('yargs')
  .options({
    'all': {
      describe: 'Show all lines',
      type: 'boolean',
      mutex: 'some',
    },
    'some': {
      describe: 'Show some lines',
      type: 'boolean',
      default: true,
      mutex: 'all',
    }
  })
  .argv
```
to indicate that the flags `--all` and `--some` are mutually exclusive _on the command line_. Of course, in this case, it does mean that `options.all` and `options.some` could end up both being set to true, and it would be up to my code to decide which takes precedence. But at least I could be sure it wasn't the _user_ that specified both.

**Closed** 2021-07-16 00:13 UTC
Labels: bug, p2
