### ISSUE TITLE
Non-global `--version` is treated as unknown option when `unknown-options-as-args` is true

### ISSUE THREAD

**Issue by isabelgiang** [yargs/yargs#2134] opened 2022-02-12 11:08 UTC
### Background

- I am using **yargs v15.0.0**.
- I have a `yargs` project that uses `unknown-options-as-args` as part of its parser configuration.
- I'm also trying to use the non-global version workaround [provided here](https://github.com/yargs/yargs/issues/1918#issuecomment-851170277) that disables the default behavior and mocks it with another command, due to having subcommands that use a `version` flag. 

### Code

```javascript
/**
 * Print current version. Only prints when no other arguments are passed.
 * ex: cli --version
 *
 * @param      {<type>}  argv    The argv
 */
 function printVersion(argv) {
    if (argv._.length === 0 && argv.version) {
        const packageJSON = require('./package.json');
        process.stdout.write(packageJSON.version + '\n')
        process.exit(0)
    }
}

const y = require('yargs')
    .parserConfiguration({
        'short-option-groups': false,
        'unknown-options-as-args': true
    })
    .version(false)
    .option('version', {
        describe: 'some option',
        type: 'boolean',
        default: true,
        global: false
    })
    .command('serve <command>', 'serve commands', 
        (yargs) => {
            return yargs
                .command('subcommand', 'subcommand commands',  
                    (yargs) => {
                        return yargs.positional( 'version', { describe: 'version of server?', type: 'number' })
                    }, 
                    (argv) => {})
        }, 
        (argv) => {}
    )
    .command('$0', 'default message', () => {}, (argv) => {
        printVersion(argv)
    })
```

### Problem

If I use a non-global `version` flag with `unknown-options-as-args`, the flag does not get parsed and is not added to the `yargs` instance.

```
> console.log(y.parse())
 { _: [ '--version' ], '$0': 'cli.js' }
```

According to the [`yargs-parser` user documentation](https://github.com/yargs/yargs-parser#unknown-options-as-args):
> An unknown option is one that is not configured in opts.

If I print the configured options for the `yargs` instance using `getOptions`, I can see that `version` is present in the printed options object. Assuming that means it's configured in `opts`, it shouldn't be an unknown option.

```
> console.log(y.getOptions()) 

{
  local: [ 'version' ],
  configObjects: [],
  array: [],
  boolean: [ 'help', 'version' ],
  string: [],
  skipValidation: [],
  count: [],
  normalize: [],
  number: [],
  hiddenOptions: [],
  narg: {},
  key: { help: true, version: true },
  alias: {},
  default: { version: true },
  defaultDescription: {},
  config: {},
  choices: {},
  demandedOptions: {},
  demandedCommands: {},
  coerce: {},
  envPrefix: undefined,
  showHiddenOpt: 'show-hidden'
}

```

How can I get this to work? Is there something else I should be trying?

**Comment by shadowspawn** [comment] 2023-07-20 08:21
I have not make complete sense of the behaviour, but looks like the problem is the configuration in the default command! This feels like overkill, but does get _your_ version handler called.

```js
    .command('$0', 'default message', (y) => {
        return y.version(false)
        .option('version', {
            describe: 'some option',
            type: 'boolean',
            default: true,
            global: false
        })
        }, (argv) => {
            printVersion(argv)
    })
```

**Comment by shadowspawn** [comment] 2023-07-20 10:16
You basically have it working, but to see `argv.version` in `printVersion` you need to define the version option in the default command too.

```
    .command('$0', 'default message', (y) => {
        return y.option('version', { type: "boolean" })
    }, (argv) => {
        printVersion(argv)
    })
```

**Comment by shadowspawn** [comment] 2024-09-07 23:22
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2024-09-07 23:22 UTC
Labels: bug, Help Wanted, p2
