### ISSUE TITLE
Disabling `'duplicate-arguments-array'` breaks variadic positional arguments.

### ISSUE THREAD

**Issue by pillowfication** [yargs/yargs#2438] opened 2024-10-22 20:24 UTC
When `'duplicate-arguments-array'` array is disabled, it seems impossible to specify multiple values for variadic positional arguments.

```typescript
import yargs from 'yargs'
import { inspect } from 'util'

yargs()
  .parserConfiguration({
    'duplicate-arguments-array': false
  })
  .command({
    command: 'cmd <pos...>',
    builder: yargs => yargs
      .positional('pos', { array: true })
      .option('opt', { array: true }),
    handler: args => { console.log(inspect(args)) }
  })
  .parse(process.argv.slice(2))
```

```bash
> node .\yargs.js cmd a b c --opt d e f      
{
  _: [ 'cmd' ],
  opt: [ 'd', 'e', 'f' ],
  pos: [ 'c' ],
  '$0': 'scripts\\test.js'
}
```

**Comment by pillowfication** [comment] 2024-10-23 19:07
Found a much older issue describing this bug: https://github.com/yargs/yargs/issues/2011

**Comment by shadowspawn** [comment] 2024-10-24 07:59
Thanks for tracking down the duplicate @pillowfication 

(I reproduced the problem.)

**Comment by pillowfication** [comment] 2024-10-24 08:10
Is there a reason this is closed as "not planned"? As it is, `'duplicate-arguments-array'` is unusable, and it's a nice feature to have for options/arguments that shouldn't be arrays.

**Comment by shadowspawn** [comment] 2024-10-24 08:32
I picked the close status that included `duplicate`, which somewhat alarming closes it as `not planned`. In fact #2011 is still open.

Duplicate of #20111

**Comment by shadowspawn** [comment] 2024-10-24 08:33
Duplicate of #20111

**Comment by shadowspawn** [comment] 2024-10-24 08:35
(Don't think the duplicate comment achieved anything!)

**Closed by shadowspawn** 2024-10-24 08:35 UTC

**Comment by shadowspawn** [comment] 2024-10-26 02:26
> When `'duplicate-arguments-array'` array is disabled,

I regret you probably tried this because I suggested it in #2437. Sorry about that!

**Comment by pillowfication** [comment] 2024-10-26 02:31
> > When `'duplicate-arguments-array'` array is disabled,
> 
> I regret you probably tried this because I suggested it in #2437. Sorry about that!

Not a problem! It's the intended behavior I wanted, just wish it didn't break something else.
