### ISSUE TITLE
add section to docs explaining common hiccups people bump into, like bash quote handling

### ISSUE THREAD

**Issue by vidavidorra** [yargs/yargs#1347] opened 2019-05-15 19:28 UTC
I'm trying to have an option that provides a string, which may start with `--`. I'm testing it now and it looks like when I pass `--` just after an option it is seen as a totally new option. See below the command I'm using and the code. I've also tried using double quotes to surround the argument, but with the same result. I'm just getting to know yargs, so maybe I'm missing something here. 

What I'd expect/want to see is that when I run `node ./dist/cli.js --thing '--hello'`, the `thing` option in `argv` would be `--hello`. When the first character is anything else than `-` it also works fine, so I can do `node ./dist/cli.js --thing '.--hello'` to result in `{ _: [], thing: '.--hello you', '$0': 'dist/cli.js' }`.

```shell
$ node ./dist/cli.js --thing '--hello'
Usage: cli.js <cmd> [options]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --thing    Add this option!                                           [string]

Unknown argument: hello
```

```ts
import yargs from 'yargs';

const argv = yargs
  .usage('Usage: $0 <cmd> [options]')
  .strict(true)
  .options({
    thing: {
      describe: 'Add this option!',
      type: 'string',
    },
  }).argv;

console.log(argv);
```

**Comment by Rytiss** [comment] 2019-06-12 11:30
I am also having this problem.

**Comment by bcoe** [comment] 2019-06-17 23:55
@Rytiss @vidavidorra unfortunately this issue can't be addressed in yargs itself, the problem is that shells like bash strip quotes, so yargs can't tell the difference between `"--hello"` and `"hello"`. You have a couple options available to you:

1. you could use the `--` operator to stop parsing: `node foo.js --foo -- --key`.
2. you could escape the string in bash: `node foo.js \"foo\"`.

I'd be open to adding a section to yargs' explaining some of these common hiccups (this quote issue comes up relatively often).

**Comment by vidavidorra** [comment] 2019-06-27 07:09
@bcoe Thanks for your response! That what you said indeed dit the trick. For reference to others, a few options that I tried that give me the expected result. The first option did not work for me. I tried `node ./dist/cli.js --thing -- "--hello -x=yes -v"` and while that does pass `--hello -x=yes -v` as argument, it does not link those to the `thing` argument. Maybe I'm doing something wrong there, but for me only the following options worked.

1. Double quotes inside single quotes or single quotes inside double quotes.
    ```shell
    $ node ./dist/cli.js --thing '"--hello -x=yes -v"'
    { _: [], thing: '--hello -x=yes -v', '$0': 'dist/cli.js' }
    ```
2. Escaped double quotes inside double quotes. Note that this does not work for single quotes (at least in my case).
    ```shell
    $ node ./dist/cli.js --thing "\"--hello -x=yes -v\""
    { _: [], thing: '--hello -x=yes -v', '$0': 'dist/cli.js' }
    ```

> I'd be open to adding a section to yargs' explaining some of these common hiccups (this quote issue comes up relatively often).

I'd think that would be helpful! Are you going to write something or do you want me to write up a small section?

**Comment by bcoe** [comment] 2019-06-27 18:28
@vidavidorra would happily accept a PR with some docs on this ... perhaps a new section of the docs like "Common Parsing Issues".

**Closed** 2019-07-13 22:58 UTC
Labels: Help Wanted, docs

**Comment by jedwards1211** [comment] 2021-03-09 06:48
@bcoe The fact that the double quotes get stripped from `'"--hello -x=yes -v"'` is another huge gotcha, the merged PR makes it seem like that's correct behavior, but it shouldn't be.  In that case the value gets passed to `process.argv` as a single string with the double quotes, so there should be no need for yargs to mess with it at all.
