### ISSUE TITLE
how can I use default command and help simultaneously

### ISSUE THREAD

**Issue by PengBoUESTC** [yargs/yargs#2312] opened 2023-03-14 05:41 UTC
yargs(hideBin(process.argv))
	.command("$0", "init rspack project", async argv => {
          consosle.log('111')
         })
        .help()
        .parse()

if the `builder` is an async function, the help command will run the builder without the help message

**Comment by shadowspawn** [comment] 2023-03-14 06:35
I have reproduced the problem (calls `exit()` before displaying help) when the default command has an async builder. Looks like a bug.

**Comment by 4i8** [comment] 2023-03-14 17:44
> yargs(hideBin(process.argv)) .command("$0", "init rspack project", async argv => { consosle.log('111') }) .help() .parse()
> 
> if the `builder` is an async function, the help command will run the builder without the help message

just use [clinei](https://www.npmjs.com/package/clinei) 🤣

**Comment by shadowspawn** [comment] 2023-04-09 00:14
I got a test working, but uncovered an interesting issue in the process. I think the async triggered during the help processing  is not returned as a promise, so calling await on the parse result does not block and allow the help to display before the test completes. I think this PR still makes sense on its own so not considering that a blocker! I'll open a PR to your branch.

**Comment by shadowspawn** [comment] 2023-07-18 08:27
This has been fixed by #2313

**Closed by shadowspawn** 2023-07-18 08:27 UTC
Labels: bug
