### ISSUE TITLE
Always get "mutually exclusive" warning when use .conflicts

### ISSUE THREAD

**Issue by gluons** [yargs/yargs#957] opened 2017-09-17 14:04 UTC
When use [`conflicts`](http://yargs.js.org/docs/#api-conflictsx-y), I always get **"mutually exclusive"** warning.

**`x.js`:**
```javascript
const argv = require('yargs')
	.help()
	.alias('help', 'h')
	.boolean('a')
	.describe('a', 'A')

	.boolean('b')
	.describe('b', 'B')

	.conflicts('a', 'b')

	.argv;

console.log(argv);
```

![_003](https://user-images.githubusercontent.com/4688092/30521555-90f160a2-9beb-11e7-8150-2cdce0c97f8a.png)

**Comment by bcoe** [comment] 2017-09-17 20:43
@gluons the problem is that you've defined `a`/`b`/ as `boolean`, so they're defaulting to `false` rather than to `undefined`. The validation API sees a value other than `undefined`, and flags the mutually exclusive arguments as having been set.

I don't think we'd want to change the default behavior of boolean variables to default to `undefined` ... this feels weird too. Perhaps you could use a custom validation function rather than `.conflicts()`.

**Comment by bcoe** [comment] 2017-09-17 20:50
closing in favor of https://github.com/yargs/yargs/issues/929

**Closed by bcoe** 2017-09-17 20:50 UTC
Labels: triaged

**Comment by gluons** [comment] 2017-09-18 03:10
Thanks
